### ISSUE TITLE
Where to get robkit?

### ISSUE THREAD

**Issue by rodier** [DarrenJDocherty/RedM-Grave-Robbing#1]
Hi, 
where players can get robbing kit?

**Comment by phantomora** [comment]
you need to add the robbing kit to shop and inventory mods

**Comment by DarrenJDocherty** [comment]
Yes, as @phantomora has described, you need to add the items to whichever store resource you use. The items it uses are: oldbuckle, oldwatch, goldring, goldtooth, oldcoin. You can change these on the first line of the server.lua.
